name: Helper

on: push

jobs:
  instructions:
    name: instructions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "BOOHOOOOO"
      - run: echo "HEllo world1211:${{secrets.GITHUB_TOKEN}}"

