name: Helper

on:
  pull_request:
    types:
      - opened
  #pull_request:
    #types:
      #- ready_for_review
        #- unlocked

jobs:
  instructions:
    name: instructions
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Label Commenter
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        run: echo "Hello world"
        #uses: peaceiris/actions-label-commenter@v1.6
        #with:
          #github_token: ${{secrets.GITHUB_TOKEN}}
