name: Helper

on: pull_request

jobs:
  instructions:
    name: instructions
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Comment
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.pulls.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Testing'
            })
